# Generated by Django 5.0.7 on 2024-11-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'custom_groups',
                'permissions': (('create_group', 'Can create group'), ('update_group', 'Can update group'), ('read_group', 'Can read group'), ('delete_group', 'Can delete group')),
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
                ('django_permission', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'custom_permissions',
                'permissions': (('create_permission', 'Can create custom permission'), ('update_permission', 'Can update custom permission'), ('read_permission', 'Can read custom permission'), ('delete_permission', 'Can delete custom permission')),
            },
        ),
        migrations.CreateModel(
            name='CustomGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.customgroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.custompermission')),
            ],
            options={
                'db_table': 'custom_group_permissions',
                'permissions': (('create_group_permission', 'Can create group permission'), ('update_group_permission', 'Can update group permission'), ('read_group_permission', 'Can read group permission'), ('delete_group_permission', 'Can delete group permission')),
                'unique_together': {('group', 'permission')},
            },
        ),
    ]
